sudo: true

language: erlang

otp_release:
  - 18.0
  - 18.1
  - 18.2

script: make update test dialyzer

before_install:
  - ./travis_install_curl.sh

addons:
  apt:
    packages:
      - libevent-dev
  # artifacts:
  #   paths:
  #     - $TRAVIS_BUILD_DIR/_build/test/logs/
