sudo: required
dist: trusty
group: edge

language: erlang

otp_release:
  - 18.0
  - 18.1
  - 18.2

script: PATH=.:$PATH make update test dialyzer coveralls

install: wget https://s3.amazonaws.com/rebar3/rebar3 && chmod 755 rebar3

cache:
  directories:
  - $HOME/.cache/rebar3/

addons:
  apt:
    packages:
      - libevent-dev
  # artifacts:
  #   paths:
  #     - $TRAVIS_BUILD_DIR/_build/test/logs/
