sudo: required
dist: trusty
group: edge

language: erlang

services:
  - docker

otp_release:
  - 18.2
  - 19.1
  - 20.0
  - 20.1

script: rebar3 update && rebar3 ct && rebar3 dialyzer && rebar3 coveralls send

cache:
  directories:
  - $HOME/.cache/rebar3/

addons:
  apt:
    packages:
      - libevent-dev
